### ISSUE TITLE
need help with alan.dart cosmos sdk

### ISSUE THREAD

**Issue by Imdavyking** [planq-network/planq#179]
__Proposal:__ [Description of the feature]
i closed the repo but it doesn't seem to work with injective grpc to send transaction
injective grpc is {  'lcdUrl': 'https://testnet.sentry.lcd.injective.network',
      'grpcUrl': 'testnet.sentry.chain.grpc.injective.network',}

__Current behavior:__ [What currently happens]

__Desired behavior:__ [What you would like to happen]

__Use case:__ [Why is this important (helps with prioritizing requests)]

Requests may be closed if we're not actively planning to work on them.

**Comment by ivanshukhov** [comment]
Closing due to wrong repository, please open that issue on the alan.dart repository

**Comment by Imdavyking** [comment]
I can't create an issue on that repo
The issue tab doesn't show

**Comment by Imdavyking** [comment]
I have actually created an issue there, got no response
I saw that you are actively improving the repo, so I decided to ask you
